
--6
SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE
FROM EMPLOYEE E1
JOIN JOB USING(JOB_CODE)
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
WHERE HIRE_DATE IN ( SELECT MIN(HIRE_DATE)
FROM EMPLOYEE E2
WHERE ENT_YN = 'N'
GROUP BY DEPT_CODE )
 ORDER BY HIRE_DATE;

--AND E1.DEPT_CODE = E2.DEPT_CODE

--부서별로 그룹을 묶을 때 퇴사한 직원을 서브쿼리에서 제외해야함
-- 왜? 부서별로 가장빠른입사자 구했을 때 D8부서는 이태림임 = 퇴사자
--> 문제점 : 부서별로 가장빠른 입사자 구해놓고 , 메인쿼리에서 퇴사자 제외해버리면
-- D8 부서는 퇴사자인 이태림이 가장 빠른 입사자이기 때문에 
-- 전체 부서중 D8부서가 아예 제외되어 버림.
--> 부서별 가장빠른입사자가 구할때(서브쿼리) 퇴사한 직원을 뺀 상태에서 그룹으로 묶으면
-- D8부서의 가장빠른입사자는 이태림제외 후 전형돈이 됨

--7
SELECT EMP_ID, EMP_NAME, JOB_NAME,
CEIL(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(EMP_NO, 1, 6) , 'RRMMDD')) / 12)  AS 나이,
TO_CHAR(SALARY * 12   + (  SALARY * 12 * NVL(BONUS, 0)   ), 'L999,999,999' ) AS 보너스포함연봉
FROM EMPLOYEE E1
JOIN JOB P ON (E1.JOB_CODE = P.JOB_CODE)
WHERE CEIL(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(EMP_NO, 1, 6) , 'RRMMDD')) / 12) 
IN ( SELECT MIN(CEIL(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(EMP_NO, 1, 6) , 'RRMMDD')) / 12) ) FROM EMPLOYEE E2 
WHERE E1.JOB_CODE = E2.JOB_CODE )
ORDER BY 4 DESC;



