SELECT EMP_NAME , DEPT_CODE, JOB_CODE
FROM EMPLOYEE
WHERE ENT_YN = 'Y' AND 
SUBSTR(EMP_NO, 8 , 1) = '2';

SELECT EMP_NAME , JOB_CODE, DEPT_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE , JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE FROM EMPLOYEE
WHERE ENT_YN = 'Y' AND 
SUBSTR(EMP_NO , 8, 1) = 2)  ;



