

SELECT STUDENT_NO , STUDENT_NAME , ENTRANCE_DATE 
FROM TB_STUDENT ts 
WHERE DEPARTMENT_NO = '002'
ORDER BY 2;

SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME LIKE '__' OR  PROFESSOR_NAME LIKE '____';
 
SELECT PROFESSOR_NAME "교수이름",
FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19' || SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYYMMDD')) / 12 )AS 나이 
FROM TB_PROFESSOR   
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 2;

SELECT SUBSTR(PROFESSOR_NAME, 2, 4)
FROM TB_PROFESSOR;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE  EXTRACT(YEAR FROM TO_DATE(SUBSTR(  STUDENT_SSN , 1, 2 ) ,'RR')) + 19 < EXTRACT(YEAR FROM ENTRANCE_DATE);



SELECT TO_CHAR(TO_DATE('2020-12-25', 'YYYY/MM/DD') , 'DAY'  )
FROM DUAL;

SELECT TO_DATE('99/10/11', 'YY/MM/DD')
FROM DUAL;

SELECT TO_DATE('49/10/11', 'YY/MM/DD')
FROM DUAL;

SELECT TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;

SELECT TO_DATE('99/10/11', 'RR/MM/DD')
FROM DUAL;


SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) < '2000';

SELECT ROUND(SUM(POINT ) / COUNT(*), 1)
FROM TB_GRADE
WHERE  STUDENT_NO = 'A517178' ;


SELECT DEPARTMENT_NO "학과번호", COUNT(*) "학생수(명)"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ;


SELECT COUNT(*) 
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

SELECT SUBSTR(TERM_NO, 1, 4) "년도", ROUND(AVG(POINT), 1)
FROM TB_GRADE
WHERE STUDENT_NO  = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;

SELECT DEPARTMENT_NO , COUNT(*) 
FROM TB_STUDENT
WHERE ABSENCE_YN  = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ;


SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME 
HAVING COUNT(STUDENT_NAME) >= 2
ORDER BY STUDENT_NAME ;


SELECT SUBSTR(TERM_NO , 1, 4) "년도",
NVL(SUBSTR(TERM_NO, 5, 2), ' ' )"학기",
ROUND(AVG(POINT) ,1 )
FROM TB_GRADE tg 
WHERE STUDENT_NO  = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO , 1, 4), SUBSTR(TERM_NO, 5, 2))
ORDER BY SUBSTR(TERM_NO , 1, 4)











