--테스트용 테이블 생성

CREATE TABLE TB_TEST(    

     TEST_NO NUMBER PRIMARY KEY,
     TEST_TITLE VARCHAR2(100) NOT NULL,
     TEST_CONTENT VARCHAR2(500) NOT NULL


);

SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY 
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
ORDER BY EMP_ID;


SELECT * FROM DEPARTMENT d ;


--6
SELECT * FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE DEPT_TITLE = '인사관리부';

--7

SELECT * FROM EMPLOYEE
WHERE SALARY IN ( SELECT SALARY FROM EMPLOYEE WHERE SALARY > 3000000  );


--8
SELECT DEPT_CODE, SUM(SALARY) AS 급여합
FROM EMPLOYEE
GROUP BY DEPT_CODE
ORDER BY 1;

--9
SELECT * FROM EMPLOYEE
WHERE EMP_NO = '621231-1985634';

--10

SELECT JOB_NAME, ROUND(AVG(SALARY), 1) AS 급여평균
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
GROUP BY JOB_NAME



SELECT * FROM EMPLOYEE;


