SELECT DEPT_CODE
FROM EMPLOYEE;

SELECT SUM(SALARY)
FROM EMPLOYEE;

SELECT DEPT_CODE ,SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT DEPT_CODE, ROUND(AVG(SALARY))
, COUNT(*)
FROM EMPLOYEE
GROUP BY DEPT_CODE
ORDER BY DEPT_CODE;


SELECT DECODE(SUBSTR(EMP_NO, 8, 1) , 1, '남', 2, '여' ), COUNT(*), SUM(SALARY)
FROM EMPLOYEE
GROUP BY DECODE(SUBSTR(EMP_NO, 8, 1) , 1, '남', 2, '여' );

SELECT DEPT_CODE,ROUND(AVG(SALARY)), COUNT(*)
FROM EMPLOYEE
WHERE DEPT_CODE IN('D5' , 'D6')
GROUP BY DEPT_CODE ;

SELECT JOB_CODE,SUM(SALARY)
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM HIRE_DATE) >= '2000'
GROUP BY JOB_CODE 
ORDER BY JOB_CODE ;

SELECT DEPT_CODE,JOB_CODE , COUNT(*)
FROM EMPLOYEE
GROUP BY DEPT_CODE, JOB_CODE
ORDER BY 1, 2 DESC;



