--1

SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
ORDER BY STUDENT_NAME;



--2

SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN ='Y'
ORDER BY 2 DESC;

--3

SELECT STUDENT_NAME,STUDENT_NO
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1) LIKE '9%'
AND SUBSTR(STUDENT_ADDRESS, 1 , 3) LIKE '경기도%';

--4
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO  = '005'
ORDER BY PROFESSOR_SSN ;

--5
SELECT STUDENT_NO , POINT 
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100' AND 
SUBSTR(TERM_NO, 1) LIKE '200402'
ORDER BY POINT DESC;

--6

SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

--7
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

--8 -- 
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_CLASS USING(CLASS_NO);


--9 --^^

SELECT CLASS_NAME AS "강의명", PROFESSOR_NAME AS "교수명"
FROM TB_PROFESSOR
JOIN TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

--10
SELECT STUDENT_NO , STUDENT_NAME, ROUND(AVG(POINT),1 )
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE DEPARTMENT_NO = '059'
GROUP BY STUDENT_NO , STUDENT_NAME
ORDER BY 3 DESC;

--11 
SELECT DEPARTMENT_NAME, STUDENT_NAME , PROFESSOR_NAME
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--12
SELECT STUDENT_NAME, SUBSTR(TERM_NO, 1, 6)
FROM TB_STUDENT 
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE SUBSTR(TERM_NO, 1, 4) LIKE '2007'
AND CLASS_NAME  = '인간관계론';

--13 ^^

SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능' 
AND PROFESSOR_NO IS NULL;


--14 &&
SELECT STUDENT_NAME, NVL(PROFESSOR_NAME, '지정교수 미지정')
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT E1 ON(E1.DEPARTMENT_NO = E2.DEPARTMENT_NO)
WHERE  DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;


-- 15
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, AVG(POINT)
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0;

--16 ^^ 

SELECT CLASS_NO, CLASS_NAME, AVG(POINT)
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO,CLASS_NAME 
ORDER BY 1;






